In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
# 1 dimensi
a=np.array([1,2,3,4,5,6])
print(a)
print(a[3])

[1 2 3 4 5 6]
4


In [7]:
# 2 dimensi
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[1])
print(b[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5


Membuat array berisi 0

In [8]:
# 1 dimensi
c=np.zeros(2)
print(c)

[0. 0.]


In [9]:
# 2 dimensi
d=np.zeros([2,3])
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


Membuat array berisi nilai 1

In [10]:
# 1 dimensi
e=np.ones(2)
print(e)

[1. 1.]


In [11]:
# 2 dimensi
f=np.ones([2,3])
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]


Membuat array berisi angka urut

In [12]:
# urut mulai 0, 1, dst
g=np.arange(2)
print(g)

[0 1]


In [17]:
# urut mulai angka awal, akhir, dan peningkatan
h=np.arange(3,15,2)
print(h)

[ 3  5  7  9 11 13]


Membuat array berdasar interval

In [19]:
i=np.linspace(10,100, num=25)
print(i)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Mengurutkan dan Menggabungkan

In [20]:
# Misal kita buat dulu suatu array
arr1=np.array([4,5,3,5,4,1])
print(arr1)
arr2=np.array([[1,4,2],[4,3,5]])
print(arr2)

[4 5 3 5 4 1]
[[1 4 2]
 [4 3 5]]


In [21]:
# Mengurutkan
x1=np.sort(arr1)
print(x1)
x2=np.sort(arr2)
print(x2)

[1 3 4 4 5 5]
[[1 2 4]
 [3 4 5]]


In [22]:
# menggabungkan 2 array (part1)
x3=np.array([1,2,3])
x4=np.array([4,5,6])
x5=np.concatenate((x3,x4))
print(x3)
print(x4)
print(x5)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [23]:
# menggabungkan 2 array (part2)
x6=np.array([[1,2],[3,4]])
x7=np.array([[5,6]])
x8=np.concatenate((x6,x7))
print(x6)
print(x7)
print(x8)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]


Bentuk dan Ukuran

In [24]:
# dimensi
arr1.ndim

1

In [25]:
arr2.ndim

2

In [26]:
# banyaknya element
arr1.size

6

In [27]:
arr2.size

6

In [28]:
# ukuran
arr1.shape

(6,)

In [29]:
arr2.shape

(2, 3)

Dapatkah kita mengubah bentuk Array?

In [30]:
y1=np.arange(10)
print(y1)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
y2=y1.reshape(2,5)
print(y2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
y3=y1.reshape(5,2)
print(y3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Mengubah 1D menjadi 2D

In [37]:
z=np.array([5,6,7,4,3,2])
z.shape

(6,)

In [38]:
print(z)

[5 6 7 4 3 2]


In [42]:
j=z[np.newaxis,:]
j.shape

(1, 6)

In [43]:
print(j)

[[5 6 7 4 3 2]]


In [45]:
k=z[:,np.newaxis]
k.shape

(6, 1)

In [46]:
print(k)

[[5]
 [6]
 [7]
 [4]
 [3]
 [2]]


Operasi Matriks

In [47]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [48]:
a3=a1+a2
print(a3)

[[ 6  8]
 [10 12]]


In [49]:
a4=a1-a2
print(a4)

[[-4 -4]
 [-4 -4]]


In [51]:
a5=a1*a2
print(a5)

[[ 5 12]
 [21 32]]


In [54]:
a6=a1.dot(a2)
print(a6)

[[19 22]
 [43 50]]


In [55]:
a7=a1@a2
print(a7)

[[19 22]
 [43 50]]


In [56]:
a8=a1.transpose()
print(a8)

[[1 3]
 [2 4]]


In [57]:
a9=np.linalg.inv(a1)
print(a9)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [58]:
a10=np.exp(a1)
print(a10)

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [59]:
a11=np.sqrt(a1)
print(a11)

[[1.         1.41421356]
 [1.73205081 2.        ]]
